project_name: numbers
num_gpus: 1

# mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (1.5, 0.5)]'

# must match your dataset's category_id.
# category_id is one_indexed,
# for example, index of '3' here is 2, while category_id of is 3
obj_list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']

compound_coef: 3
num_workers: 4
batch_size: 3
head_only: False    # whether finetune only the regressor and the classifier
lr: 0.001
optim: 'adamw'
num_epochs: 5
val_interval: 1     # Number of epoches between valing phases
save_interval: 1000      # Number of steps between saving
es_min_delta: 0.0    # Early stopping's parameter: minimum change loss to qualify as an improvement
es_patience: 0       # Early stopping's parameter: number of epochs with no improvement after which training will be stopped. Set to 0 to disable
log_path: 'logs/'
load_weights: 'efficientdet-d3.pth'     # whether to load weights from a checkpoint, set None to initialize, set 'last' to load last checkpoint
saved_path: 'logs/'
debug: False
custom_size: 768